# Generated by Django 2.1.7 on 2019-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190317_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
