# Generated by Django 2.1.7 on 2019-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190317_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100, verbose_name='Your first name')),
                ('last', models.CharField(max_length=100, verbose_name='Your last name')),
                ('sq_ft', models.CharField(max_length=100, verbose_name='How much square footage?')),
                ('beds', models.CharField(max_length=100, verbose_name='How many beds?')),
                ('baths', models.CharField(max_length=100, verbose_name='How many baths?')),
                ('email', models.EmailField(max_length=100, verbose_name="What's your email?")),
                ('phone', models.CharField(max_length=100, verbose_name="What's your phone number?")),
                ('property_type', models.CharField(choices=[('SINGLE', 'Single Property'), ('CONDO', 'Condo/Townhouse'), ('INCOMEPROP', 'Income Property')], max_length=20, verbose_name="What's the property type?")),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('move_in_date', models.CharField(max_length=100, verbose_name="What's the approximate move in date?")),
                ('preffered_method_of_contact', models.CharField(max_length=100, verbose_name="What's your preffered method of contact?")),
                ('description', models.TextField(max_length=1000, verbose_name='Description of the property')),
            ],
        ),
    ]
