# Generated by Django 2.1.7 on 2019-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_newlead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='newlead',
            name='first',
        ),
        migrations.RemoveField(
            model_name='newlead',
            name='last',
        ),
        migrations.RemoveField(
            model_name='newlead',
            name='state',
        ),
        migrations.AddField(
            model_name='newlead',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Your name'),
        ),
    ]
