# Generated by Django 2.1.7 on 2019-03-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20190318_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mls_link',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='MLS Link'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=None, upload_to='properties/static/properties/uploads/'),
        ),
    ]
