# Generated by Django 2.1.7 on 2019-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20190318_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlead',
            name='property_type',
            field=models.CharField(choices=[('SINGLE', 'Single Property'), ('CONDO', 'Condo/Townhouse'), ('INCOMEPROP', 'Income Property'), ('OTHER', 'Other')], max_length=20, verbose_name="What's the property type?"),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=None, upload_to='properties/'),
        ),
    ]
